name: Compile thesis

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Inkscape
      run: apt install inkscape
      
    - uses: xu-cheng/texlive-action/full@v1
      with:
        run: VERBOSE=true make

    - name: Rename PDF
      run: mv main.pdf thesis.pdf

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: thesis
        path: ./thesis.pdf

